EmbeddedPkg: Add cast from (void*) for VS2017 build
The following build configrations:
build -b DEBUG -a AARCH64 -t VS2017 -p edk2\EmbeddedPkg\EmbeddedPkg.dsc
build -b NOOPT -a AARCH64 -t VS2017 -p edk2\EmbeddedPkg\EmbeddedPkg.dsc
build -b RELEASE -a AARCH64 -t VS2017 -p edk2\EmbeddedPkg\EmbeddedPkg.dsc

are generating the following build errors:
edk2\EmbeddedPkg\Library\AndroidBootImgLib\AndroidBootImgLib.c(100):
error C2036: 'void *': unknown size
edk2\EmbeddedPkg\Library\AndroidBootImgLib\AndroidBootImgLib.c(347):
error C2036: 'void *': unknown size

Since the size of void* depends on the architecture, it can be
dangerous to use void* pointer arithmetic. Plus the C99 doesn't state
that void* pointer arithmetic is allowed.
This patch adds a cast to fix the Visual Studio errors reported.

Signed-off-by: Pierre Gondois <pierre.gondois@arm.com>